version: "3"

services:
  postgres:
    image: postgres:13.2
    command: postgres -N 2000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - local
    ports:
      - 15432:5432

  redis:
    image: redis:6.2.2
    # command: sh -c "redis-server --requirepass password"
    command: sh -c "redis-server"
    networks:
      - local
    ports:
      - 16379:6379

  rabbitmq:
    # image: ipelegi/rabbitmq:latest
    # 依赖延迟插件（https://www.cnblogs.com/zengdingding/p/16641869.html）
    # todo 数据持续化到主机，防止数据丢失！！！
    image: rabbitmq:management
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - local

  elasticsearch:
    container_name: 'elasticsearch'
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - xpack.security.enabled=false
      - 'discovery.type=single-node'
    networks:
      - local
    ports:
      - 19200:9200

networks:
  local:
    driver: bridge
