# https://taskfile.dev
version: "3"
tasks:
  dev: yarn dev
  build: yarn build
  start: yarn start
  fmt: yarn format

  # brew install redis
  brewredislog: tail -f /opt/homebrew/var/log/redis.log
  pg-fair: docker-compose exec -it postgres psql -U postgres zkfair_testnet
  pg-x1: docker-compose exec -it postgres psql -U postgres x1testnet
  pg: docker-compose exec -it postgres psql -U postgres

  rabbitlog: docker-compose logs -f rabbitmq
  rabbit: docker-compose exec -i rabbitmq bash

  # guest/guest
  open-rabbit: open http://localhost:15672/#/
  a1:
    cmds:
      # https://api.reservoir.tools/chain/stats/v1
      - |
        curl --request GET \
        --url http://localhost:3006/chain/stats/v1 \
        --header 'accept: */*' \
        --header 'x-api-key: adminApiKeyTest' | jq
  t1:
    cmds:
      - |
        echo hi es service
        curl http://localhost:9200
        echo "pg with password: password"
        # psql -p 15432 -U postgres -h 127.0.0.1 --password
